# Importing libraries

In [27]:
import numpy as np
import pandas as pd


# Importing dataset

In [28]:
dataset=pd.read_csv('../datasets/Data.csv')
print(dataset)
X=dataset.iloc[:,:-1].values
print(X)
Y=dataset.iloc[:,3].values

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# handling missing values

In [29]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer= imputer.fit(X[:,1:3])
print(imputer)
X[:,1:3]=imputer.transform(X[:,1:3])
print(X[:,1:3])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)
[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 63777.77777777778]
 [35.0 58000.0]
 [38.77777777777778 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


# Encoding Categorical data 

In [32]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])
print(X[:,0])

[0 2 1 2 1 0 2 0 1 0]


In [36]:
#creating a dummy variable
from sklearn.compose import ColumnTransformer 
ct=ColumnTransformer([('encoder',OneHotEncoder(),[0])],remainder='passthrough')
#onehotencoder=OneHotEncoder(categorical_features=[0])
X=ct.fit_transform(X)
labelencoder_Y=LabelEncoder()
Y=labelencoder_Y.fit_transform(Y)


# split the dataset into training and testing sets

In [39]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,Y_train,Y_test=tts(X,Y,test_size=0.2,random_state=0)

In [40]:
print(X_train,X_test,Y_train,Y_test)

[[1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]] [[1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]] [1 1 1 0 1 0 0 1] [0 0]


# Feature Scaling

In [41]:
from sklearn.preprocessing import StandardScaler
Sc_X=StandardScaler()
X_train=Sc_X.fit_transform(X_train)
X_test=Sc_X.fit_transform(X_test)
print(X_train,X_test)

[[ 1.         -1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [-1.          1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [ 1.         -1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [ 1.         -1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [-1.          1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [ 1.         -1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [-1.          1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [-1.          1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]] [[ 0.  0.  0.  0. -1. -1.]
 [ 0.  0.  0.  0.  1.  1.]]
